variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.8.2-adoptopenjdk-16-openj9
  cache:
    key: maven-cache
    paths:
    - .m2/repository
  before_script:
    - apt-get update
    - apt-get install -y openjfx --no-install-recommends
    - rm -rf /var/lib/apt/lists/*

stages:
  - build
  - test_core
  - test_fx
  - test_manual

build:
  stage: build
  script: 
    - mvn clean install -DskipTests

test_core:
  stage: test_core
  needs: [build]
  script:
    - mvn install -DskipTests
    - mvn jacoco:prepare-agent test -pl core jacoco:report
    - cat core/target/site/jacoco/index.html

test_fx:
  stage: test_fx
  needs: [build]
  script:
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test -pl marxbankfx jacoco:report
    - cat marxbankfx/target/site/jacoco/index.html

test_manual:
  stage: test_manual
  needs: [build]
  script:
    - mvn clean install -DskipTests
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test jacoco:report
    - cat marxbankfx/target/site/jacoco/index.html
    - cat core/target/site/jacoco/index.html
  when: manual

  
