variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

default:
  image: maven:3.8.2-adoptopenjdk-16-openj9
  cache:
    key: maven-cache
    paths:
    - .m2/repository
  before_script:
    - apt-get update
    - apt-get install -y openjfx --no-install-recommends
    - rm -rf /var/lib/apt/lists/*

stages:
  - build
  - test_core
  - test_storage
  - test_fx
  - test_backend
  - test_vue
  - test_manual
  

build:
  stage: build
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script: 
    - mvn clean install -DskipTests

test_core:
  stage: test_core
  needs: [build]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script:
    - mvn jacoco:prepare-agent test -pl core jacoco:report
    - cat core/target/site/jacoco/index.html

test_storage:
  stage: test_storage
  needs: [build, test_core]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script:
    - mvn jacoco:prepare-agent test -pl storage jacoco:report
    - cat storage/target/site/jacoco/index.html

test_fx:
  stage: test_fx
  needs: [build, test_core]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script:
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test -pl marxbankfx jacoco:report
    - cat marxbankfx/target/site/jacoco/index.html

test_vue:
  stage: test_vue
  needs: [build]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - cd marxbankvue
    - mvn install 

test_manual:
  stage: test_manual
  needs: [build]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script:
    - mvn clean install -DskipTests
    - mvn -Dtestfx.robot=glass -Dtestfx.headless=true jacoco:prepare-agent test jacoco:report
    - cat core/target/site/jacoco/index.html
    - cat marxbankfx/target/site/jacoco/index.html
    - cat storage/target/site/jacoco/index.html
    - cat backend/target/site/jacoco/index.html
  when: manual

test_backend:
  stage: test_backend
  needs: [build, test_core]
  retry:
    max: 1
    when:
      - unknown_failure
      - runner_system_failure
      - job_execution_timeout
      - data_integrity_failure
  script:
    - mvn install -DskipTests
    - mvn jacoco:prepare-agent test -pl backend jacoco:report
    - cat backend/target/site/jacoco/index.html

  
